/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SlugTrabalheConoscoRouteImport } from './routes/$slug.trabalhe-conosco'
import { Route as SlugReservasRouteImport } from './routes/$slug.reservas'
import { Route as SlugGaleriaRouteImport } from './routes/$slug.galeria'
import { Route as SlugEventosRouteImport } from './routes/$slug.eventos'
import { Route as SlugEnviarRouteImport } from './routes/$slug.enviar'
import { Route as SlugEnviadoRouteImport } from './routes/$slug.enviado'
import { Route as SlugAdminRouteImport } from './routes/$slug.admin'
import { Route as SlugAdminIndexRouteImport } from './routes/$slug.admin.index'
import { Route as SlugFotoPhotoIdRouteImport } from './routes/$slug.foto.$photoId'
import { Route as SlugAdminReservasRouteImport } from './routes/$slug.admin.reservas'
import { Route as SlugAdminQrCodesRouteImport } from './routes/$slug.admin.qr-codes'
import { Route as SlugAdminModeracaoRouteImport } from './routes/$slug.admin.moderacao'
import { Route as SlugAdminLoginRouteImport } from './routes/$slug.admin.login'
import { Route as SlugAdminCurriculosRouteImport } from './routes/$slug.admin.curriculos'
import { Route as SlugAdminConteudoRouteImport } from './routes/$slug.admin.conteudo'
import { Route as SlugAdminConfigRouteImport } from './routes/$slug.admin.config'

const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const SlugTrabalheConoscoRoute = SlugTrabalheConoscoRouteImport.update({
  id: '/trabalhe-conosco',
  path: '/trabalhe-conosco',
  getParentRoute: () => SlugRoute,
} as any)
const SlugReservasRoute = SlugReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => SlugRoute,
} as any)
const SlugGaleriaRoute = SlugGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => SlugRoute,
} as any)
const SlugEventosRoute = SlugEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => SlugRoute,
} as any)
const SlugEnviarRoute = SlugEnviarRouteImport.update({
  id: '/enviar',
  path: '/enviar',
  getParentRoute: () => SlugRoute,
} as any)
const SlugEnviadoRoute = SlugEnviadoRouteImport.update({
  id: '/enviado',
  path: '/enviado',
  getParentRoute: () => SlugRoute,
} as any)
const SlugAdminRoute = SlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SlugRoute,
} as any)
const SlugAdminIndexRoute = SlugAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugFotoPhotoIdRoute = SlugFotoPhotoIdRouteImport.update({
  id: '/foto/$photoId',
  path: '/foto/$photoId',
  getParentRoute: () => SlugRoute,
} as any)
const SlugAdminReservasRoute = SlugAdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminQrCodesRoute = SlugAdminQrCodesRouteImport.update({
  id: '/qr-codes',
  path: '/qr-codes',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminModeracaoRoute = SlugAdminModeracaoRouteImport.update({
  id: '/moderacao',
  path: '/moderacao',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminLoginRoute = SlugAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminCurriculosRoute = SlugAdminCurriculosRouteImport.update({
  id: '/curriculos',
  path: '/curriculos',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminConteudoRoute = SlugAdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminConfigRoute = SlugAdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => SlugAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/$slug/admin': typeof SlugAdminRouteWithChildren
  '/$slug/enviado': typeof SlugEnviadoRoute
  '/$slug/enviar': typeof SlugEnviarRoute
  '/$slug/eventos': typeof SlugEventosRoute
  '/$slug/galeria': typeof SlugGaleriaRoute
  '/$slug/reservas': typeof SlugReservasRoute
  '/$slug/trabalhe-conosco': typeof SlugTrabalheConoscoRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/admin/config': typeof SlugAdminConfigRoute
  '/$slug/admin/conteudo': typeof SlugAdminConteudoRoute
  '/$slug/admin/curriculos': typeof SlugAdminCurriculosRoute
  '/$slug/admin/login': typeof SlugAdminLoginRoute
  '/$slug/admin/moderacao': typeof SlugAdminModeracaoRoute
  '/$slug/admin/qr-codes': typeof SlugAdminQrCodesRoute
  '/$slug/admin/reservas': typeof SlugAdminReservasRoute
  '/$slug/foto/$photoId': typeof SlugFotoPhotoIdRoute
  '/$slug/admin/': typeof SlugAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug/enviado': typeof SlugEnviadoRoute
  '/$slug/enviar': typeof SlugEnviarRoute
  '/$slug/eventos': typeof SlugEventosRoute
  '/$slug/galeria': typeof SlugGaleriaRoute
  '/$slug/reservas': typeof SlugReservasRoute
  '/$slug/trabalhe-conosco': typeof SlugTrabalheConoscoRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/admin/config': typeof SlugAdminConfigRoute
  '/$slug/admin/conteudo': typeof SlugAdminConteudoRoute
  '/$slug/admin/curriculos': typeof SlugAdminCurriculosRoute
  '/$slug/admin/login': typeof SlugAdminLoginRoute
  '/$slug/admin/moderacao': typeof SlugAdminModeracaoRoute
  '/$slug/admin/qr-codes': typeof SlugAdminQrCodesRoute
  '/$slug/admin/reservas': typeof SlugAdminReservasRoute
  '/$slug/foto/$photoId': typeof SlugFotoPhotoIdRoute
  '/$slug/admin': typeof SlugAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/$slug/admin': typeof SlugAdminRouteWithChildren
  '/$slug/enviado': typeof SlugEnviadoRoute
  '/$slug/enviar': typeof SlugEnviarRoute
  '/$slug/eventos': typeof SlugEventosRoute
  '/$slug/galeria': typeof SlugGaleriaRoute
  '/$slug/reservas': typeof SlugReservasRoute
  '/$slug/trabalhe-conosco': typeof SlugTrabalheConoscoRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/admin/config': typeof SlugAdminConfigRoute
  '/$slug/admin/conteudo': typeof SlugAdminConteudoRoute
  '/$slug/admin/curriculos': typeof SlugAdminCurriculosRoute
  '/$slug/admin/login': typeof SlugAdminLoginRoute
  '/$slug/admin/moderacao': typeof SlugAdminModeracaoRoute
  '/$slug/admin/qr-codes': typeof SlugAdminQrCodesRoute
  '/$slug/admin/reservas': typeof SlugAdminReservasRoute
  '/$slug/foto/$photoId': typeof SlugFotoPhotoIdRoute
  '/$slug/admin/': typeof SlugAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/$slug/admin'
    | '/$slug/enviado'
    | '/$slug/enviar'
    | '/$slug/eventos'
    | '/$slug/galeria'
    | '/$slug/reservas'
    | '/$slug/trabalhe-conosco'
    | '/$slug/'
    | '/$slug/admin/config'
    | '/$slug/admin/conteudo'
    | '/$slug/admin/curriculos'
    | '/$slug/admin/login'
    | '/$slug/admin/moderacao'
    | '/$slug/admin/qr-codes'
    | '/$slug/admin/reservas'
    | '/$slug/foto/$photoId'
    | '/$slug/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug/enviado'
    | '/$slug/enviar'
    | '/$slug/eventos'
    | '/$slug/galeria'
    | '/$slug/reservas'
    | '/$slug/trabalhe-conosco'
    | '/$slug'
    | '/$slug/admin/config'
    | '/$slug/admin/conteudo'
    | '/$slug/admin/curriculos'
    | '/$slug/admin/login'
    | '/$slug/admin/moderacao'
    | '/$slug/admin/qr-codes'
    | '/$slug/admin/reservas'
    | '/$slug/foto/$photoId'
    | '/$slug/admin'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/$slug/admin'
    | '/$slug/enviado'
    | '/$slug/enviar'
    | '/$slug/eventos'
    | '/$slug/galeria'
    | '/$slug/reservas'
    | '/$slug/trabalhe-conosco'
    | '/$slug/'
    | '/$slug/admin/config'
    | '/$slug/admin/conteudo'
    | '/$slug/admin/curriculos'
    | '/$slug/admin/login'
    | '/$slug/admin/moderacao'
    | '/$slug/admin/qr-codes'
    | '/$slug/admin/reservas'
    | '/$slug/foto/$photoId'
    | '/$slug/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/trabalhe-conosco': {
      id: '/$slug/trabalhe-conosco'
      path: '/trabalhe-conosco'
      fullPath: '/$slug/trabalhe-conosco'
      preLoaderRoute: typeof SlugTrabalheConoscoRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/reservas': {
      id: '/$slug/reservas'
      path: '/reservas'
      fullPath: '/$slug/reservas'
      preLoaderRoute: typeof SlugReservasRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/galeria': {
      id: '/$slug/galeria'
      path: '/galeria'
      fullPath: '/$slug/galeria'
      preLoaderRoute: typeof SlugGaleriaRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/eventos': {
      id: '/$slug/eventos'
      path: '/eventos'
      fullPath: '/$slug/eventos'
      preLoaderRoute: typeof SlugEventosRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/enviar': {
      id: '/$slug/enviar'
      path: '/enviar'
      fullPath: '/$slug/enviar'
      preLoaderRoute: typeof SlugEnviarRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/enviado': {
      id: '/$slug/enviado'
      path: '/enviado'
      fullPath: '/$slug/enviado'
      preLoaderRoute: typeof SlugEnviadoRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/admin': {
      id: '/$slug/admin'
      path: '/admin'
      fullPath: '/$slug/admin'
      preLoaderRoute: typeof SlugAdminRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/admin/': {
      id: '/$slug/admin/'
      path: '/'
      fullPath: '/$slug/admin/'
      preLoaderRoute: typeof SlugAdminIndexRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/foto/$photoId': {
      id: '/$slug/foto/$photoId'
      path: '/foto/$photoId'
      fullPath: '/$slug/foto/$photoId'
      preLoaderRoute: typeof SlugFotoPhotoIdRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/admin/reservas': {
      id: '/$slug/admin/reservas'
      path: '/reservas'
      fullPath: '/$slug/admin/reservas'
      preLoaderRoute: typeof SlugAdminReservasRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/qr-codes': {
      id: '/$slug/admin/qr-codes'
      path: '/qr-codes'
      fullPath: '/$slug/admin/qr-codes'
      preLoaderRoute: typeof SlugAdminQrCodesRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/moderacao': {
      id: '/$slug/admin/moderacao'
      path: '/moderacao'
      fullPath: '/$slug/admin/moderacao'
      preLoaderRoute: typeof SlugAdminModeracaoRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/login': {
      id: '/$slug/admin/login'
      path: '/login'
      fullPath: '/$slug/admin/login'
      preLoaderRoute: typeof SlugAdminLoginRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/curriculos': {
      id: '/$slug/admin/curriculos'
      path: '/curriculos'
      fullPath: '/$slug/admin/curriculos'
      preLoaderRoute: typeof SlugAdminCurriculosRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/conteudo': {
      id: '/$slug/admin/conteudo'
      path: '/conteudo'
      fullPath: '/$slug/admin/conteudo'
      preLoaderRoute: typeof SlugAdminConteudoRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/config': {
      id: '/$slug/admin/config'
      path: '/config'
      fullPath: '/$slug/admin/config'
      preLoaderRoute: typeof SlugAdminConfigRouteImport
      parentRoute: typeof SlugAdminRoute
    }
  }
}

interface SlugAdminRouteChildren {
  SlugAdminConfigRoute: typeof SlugAdminConfigRoute
  SlugAdminConteudoRoute: typeof SlugAdminConteudoRoute
  SlugAdminCurriculosRoute: typeof SlugAdminCurriculosRoute
  SlugAdminLoginRoute: typeof SlugAdminLoginRoute
  SlugAdminModeracaoRoute: typeof SlugAdminModeracaoRoute
  SlugAdminQrCodesRoute: typeof SlugAdminQrCodesRoute
  SlugAdminReservasRoute: typeof SlugAdminReservasRoute
  SlugAdminIndexRoute: typeof SlugAdminIndexRoute
}

const SlugAdminRouteChildren: SlugAdminRouteChildren = {
  SlugAdminConfigRoute: SlugAdminConfigRoute,
  SlugAdminConteudoRoute: SlugAdminConteudoRoute,
  SlugAdminCurriculosRoute: SlugAdminCurriculosRoute,
  SlugAdminLoginRoute: SlugAdminLoginRoute,
  SlugAdminModeracaoRoute: SlugAdminModeracaoRoute,
  SlugAdminQrCodesRoute: SlugAdminQrCodesRoute,
  SlugAdminReservasRoute: SlugAdminReservasRoute,
  SlugAdminIndexRoute: SlugAdminIndexRoute,
}

const SlugAdminRouteWithChildren = SlugAdminRoute._addFileChildren(
  SlugAdminRouteChildren,
)

interface SlugRouteChildren {
  SlugAdminRoute: typeof SlugAdminRouteWithChildren
  SlugEnviadoRoute: typeof SlugEnviadoRoute
  SlugEnviarRoute: typeof SlugEnviarRoute
  SlugEventosRoute: typeof SlugEventosRoute
  SlugGaleriaRoute: typeof SlugGaleriaRoute
  SlugReservasRoute: typeof SlugReservasRoute
  SlugTrabalheConoscoRoute: typeof SlugTrabalheConoscoRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugFotoPhotoIdRoute: typeof SlugFotoPhotoIdRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugAdminRoute: SlugAdminRouteWithChildren,
  SlugEnviadoRoute: SlugEnviadoRoute,
  SlugEnviarRoute: SlugEnviarRoute,
  SlugEventosRoute: SlugEventosRoute,
  SlugGaleriaRoute: SlugGaleriaRoute,
  SlugReservasRoute: SlugReservasRoute,
  SlugTrabalheConoscoRoute: SlugTrabalheConoscoRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugFotoPhotoIdRoute: SlugFotoPhotoIdRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
